[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Amandus Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10.0"
crossbeam-utils = "0.5.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]
